name: lostmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15

  # Tambahan: Device Preview
  device_preview: ^1.1.0
  pocketbase: ^0.22.0
  # riverpod: ^2.6.1  
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
 
 